# Generated by Django 5.2 on 2025-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_point', '0003_remove_equipment_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='ai_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
